version: '3.1'
services:
  split-wise:
      container_name: split-wise
      build: .
      ports:
        - "8080:8080"
      restart: on-failure
      volumes:
        - split-wise-app:/usr/src/split-wise-app/
      depends_on:
        -   postgres
      networks:
        - split-wise-network


  postgres:
       image:  postgres:latest
       container_name: postgres-db
       ports:
         - "5432:5432"
       environment:
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PASSWORD}
         - POSTGRES_DB=${DB_NAME}
         - DATABASE_HOST=${DB_HOST}
       volumes:
         - database_postgres:/var/lib/postgresql/data
       networks:
         - split-wise-network

  pgadmin:
       image: dpage/pgadmin4
       container_name: pgadmin_container
       depends_on:
         - postgres
       environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
       ports:
         - "5050:80"
       restart: unless-stopped
       networks:
         - split-wise-network


volumes:
  split-wise-app:
  database_postgres:

networks:
  split-wise-network:
    driver: bridge
